package com.hzsparrow.business.base.mapper;

import com.hzsparrow.business.base.entity.HzsDictionaryDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HzsDictionaryDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsddId);

    int deleteByHsdtId(String hsdtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    int insert(HzsDictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    HzsDictionaryDetail selectByPrimaryKey(String hsddId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    List<HzsDictionaryDetail> pageFindByHsdtId(@Param("hsdtId") String hsdtId, @Param("hsddName") String hsddName, @Param("parentId") String parentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsDictionaryDetail record);

    Integer getMaxSortNum(@Param("hsdtId") String hsdtId);

    Integer isHaveSameName(@Param("hsdtId") String hsdtId, @Param("hsddName") String hsddName, @Param("hsddId") String hsddId);
}