package com.hzsparrow.business.base.mapper;

import com.hzsparrow.business.base.entity.HzsDictionaryType;

import java.util.List;

public interface HzsDictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsdtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_type
     *
     * @mbg.generated
     */
    int insert(HzsDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_type
     *
     * @mbg.generated
     */
    HzsDictionaryType selectByPrimaryKey(String hsdtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_type
     *
     * @mbg.generated
     */
    List<HzsDictionaryType> pageFindAll(String hsdtName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsDictionaryType record);
}