package com.hzsparrow.business.base.mapper;

import com.hzsparrow.business.base.entity.HzsMenu;

import java.util.List;

public interface HzsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    int insert(HzsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    HzsMenu selectByPrimaryKey(String hsmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    List<HzsMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsMenu record);
}