package com.hzsparrow.business.base.mapper;

import com.hzsparrow.business.base.entity.HzsRole;

import java.util.List;

public interface HzsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role
     *
     * @mbg.generated
     */
    int insert(HzsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role
     *
     * @mbg.generated
     */
    HzsRole selectByPrimaryKey(String hsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role
     *
     * @mbg.generated
     */
    List<HzsRole> selectAll(String hsrName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsRole record);

    Integer getMaxSort();
}