package com.hzsparrow.boot.base.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HzsFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.hsf_id
     *
     * @mbg.generated
     */
    private String hsfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_old_name
     *
     * @mbg.generated
     */
    private String fileOldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_new_name
     *
     * @mbg.generated
     */
    private String fileNewName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_suffix
     *
     * @mbg.generated
     */
    private String fileSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_size
     *
     * @mbg.generated
     */
    private BigDecimal fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_save_addr
     *
     * @mbg.generated
     */
    private Integer fileSaveAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.upload_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.upload_id
     *
     * @mbg.generated
     */
    private String uploadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.upload_name
     *
     * @mbg.generated
     */
    private String uploadName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_ref_flag
     *
     * @mbg.generated
     */
    private String fileRefFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_file.file_reg_id
     *
     * @mbg.generated
     */
    private String fileRegId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hzs_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.hsf_id
     *
     * @return the value of hzs_file.hsf_id
     *
     * @mbg.generated
     */
    public String getHsfId() {
        return hsfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.hsf_id
     *
     * @param hsfId the value for hzs_file.hsf_id
     *
     * @mbg.generated
     */
    public void setHsfId(String hsfId) {
        this.hsfId = hsfId == null ? null : hsfId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_old_name
     *
     * @return the value of hzs_file.file_old_name
     *
     * @mbg.generated
     */
    public String getFileOldName() {
        return fileOldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_old_name
     *
     * @param fileOldName the value for hzs_file.file_old_name
     *
     * @mbg.generated
     */
    public void setFileOldName(String fileOldName) {
        this.fileOldName = fileOldName == null ? null : fileOldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_new_name
     *
     * @return the value of hzs_file.file_new_name
     *
     * @mbg.generated
     */
    public String getFileNewName() {
        return fileNewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_new_name
     *
     * @param fileNewName the value for hzs_file.file_new_name
     *
     * @mbg.generated
     */
    public void setFileNewName(String fileNewName) {
        this.fileNewName = fileNewName == null ? null : fileNewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_suffix
     *
     * @return the value of hzs_file.file_suffix
     *
     * @mbg.generated
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_suffix
     *
     * @param fileSuffix the value for hzs_file.file_suffix
     *
     * @mbg.generated
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_size
     *
     * @return the value of hzs_file.file_size
     *
     * @mbg.generated
     */
    public BigDecimal getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_size
     *
     * @param fileSize the value for hzs_file.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_path
     *
     * @return the value of hzs_file.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_path
     *
     * @param filePath the value for hzs_file.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_save_addr
     *
     * @return the value of hzs_file.file_save_addr
     *
     * @mbg.generated
     */
    public Integer getFileSaveAddr() {
        return fileSaveAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_save_addr
     *
     * @param fileSaveAddr the value for hzs_file.file_save_addr
     *
     * @mbg.generated
     */
    public void setFileSaveAddr(Integer fileSaveAddr) {
        this.fileSaveAddr = fileSaveAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.upload_time
     *
     * @return the value of hzs_file.upload_time
     *
     * @mbg.generated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.upload_time
     *
     * @param uploadTime the value for hzs_file.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.upload_id
     *
     * @return the value of hzs_file.upload_id
     *
     * @mbg.generated
     */
    public String getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.upload_id
     *
     * @param uploadId the value for hzs_file.upload_id
     *
     * @mbg.generated
     */
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId == null ? null : uploadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.upload_name
     *
     * @return the value of hzs_file.upload_name
     *
     * @mbg.generated
     */
    public String getUploadName() {
        return uploadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.upload_name
     *
     * @param uploadName the value for hzs_file.upload_name
     *
     * @mbg.generated
     */
    public void setUploadName(String uploadName) {
        this.uploadName = uploadName == null ? null : uploadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_ref_flag
     *
     * @return the value of hzs_file.file_ref_flag
     *
     * @mbg.generated
     */
    public String getFileRefFlag() {
        return fileRefFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_ref_flag
     *
     * @param fileRefFlag the value for hzs_file.file_ref_flag
     *
     * @mbg.generated
     */
    public void setFileRefFlag(String fileRefFlag) {
        this.fileRefFlag = fileRefFlag == null ? null : fileRefFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_file.file_reg_id
     *
     * @return the value of hzs_file.file_reg_id
     *
     * @mbg.generated
     */
    public String getFileRegId() {
        return fileRegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_file.file_reg_id
     *
     * @param fileRegId the value for hzs_file.file_reg_id
     *
     * @mbg.generated
     */
    public void setFileRegId(String fileRegId) {
        this.fileRegId = fileRegId == null ? null : fileRegId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hsfId=").append(hsfId);
        sb.append(", fileOldName=").append(fileOldName);
        sb.append(", fileNewName=").append(fileNewName);
        sb.append(", fileSuffix=").append(fileSuffix);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", filePath=").append(filePath);
        sb.append(", fileSaveAddr=").append(fileSaveAddr);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", uploadId=").append(uploadId);
        sb.append(", uploadName=").append(uploadName);
        sb.append(", fileRefFlag=").append(fileRefFlag);
        sb.append(", fileRegId=").append(fileRegId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}