package com.hzsparrow.boot.base.entity;

import com.hzsparrow.framework.utils.tree.TreeModelSource;

import java.io.Serializable;

public class HzsMenu implements Serializable, TreeModelSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.hsm_id
     *
     * @mbg.generated
     */
    private String hsmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.hsm_name
     *
     * @mbg.generated
     */
    private String hsmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.hsm_type
     *
     * @mbg.generated
     */
    private Integer hsmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_menu.sort_num
     *
     * @mbg.generated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.hsm_id
     *
     * @return the value of hzs_menu.hsm_id
     * @mbg.generated
     */
    public String getHsmId() {
        return hsmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.hsm_id
     *
     * @param hsmId the value for hzs_menu.hsm_id
     * @mbg.generated
     */
    public void setHsmId(String hsmId) {
        this.hsmId = hsmId == null ? null : hsmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.hsm_name
     *
     * @return the value of hzs_menu.hsm_name
     * @mbg.generated
     */
    public String getHsmName() {
        return hsmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.hsm_name
     *
     * @param hsmName the value for hzs_menu.hsm_name
     * @mbg.generated
     */
    public void setHsmName(String hsmName) {
        this.hsmName = hsmName == null ? null : hsmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.parent_id
     *
     * @return the value of hzs_menu.parent_id
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.parent_id
     *
     * @param parentId the value for hzs_menu.parent_id
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.url
     *
     * @return the value of hzs_menu.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.url
     *
     * @param url the value for hzs_menu.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.hsm_type
     *
     * @return the value of hzs_menu.hsm_type
     * @mbg.generated
     */
    public Integer getHsmType() {
        return hsmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.hsm_type
     *
     * @param hsmType the value for hzs_menu.hsm_type
     * @mbg.generated
     */
    public void setHsmType(Integer hsmType) {
        this.hsmType = hsmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.state
     *
     * @return the value of hzs_menu.state
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.state
     *
     * @param state the value for hzs_menu.state
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.icon
     *
     * @return the value of hzs_menu.icon
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.icon
     *
     * @param icon the value for hzs_menu.icon
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_menu.sort_num
     *
     * @return the value of hzs_menu.sort_num
     * @mbg.generated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_menu.sort_num
     *
     * @param sortNum the value for hzs_menu.sort_num
     * @mbg.generated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hsmId=").append(hsmId);
        sb.append(", hsmName=").append(hsmName);
        sb.append(", parentId=").append(parentId);
        sb.append(", url=").append(url);
        sb.append(", hsmType=").append(hsmType);
        sb.append(", state=").append(state);
        sb.append(", icon=").append(icon);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public Object getTreeModelId() {
        return getHsmId();
    }

    @Override
    public String getTreeModelName() {
        return getHsmName();
    }

    @Override
    public Object getTreeModelParentId() {
        return getParentId();
    }
}