package com.hzsparrow.boot.base.mapper;

import com.hzsparrow.boot.base.entity.HzsRoleMenu;
import java.util.List;

public interface HzsRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsrmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role_menu
     *
     * @mbg.generated
     */
    int insert(HzsRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role_menu
     *
     * @mbg.generated
     */
    HzsRoleMenu selectByPrimaryKey(String hsrmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role_menu
     *
     * @mbg.generated
     */
    List<HzsRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsRoleMenu record);
}