package com.hzsparrow.boot.base.mapper;

import com.hzsparrow.boot.base.entity.HzsSysConfig;
import java.util.List;

public interface HzsSysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hsscId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    int insert(HzsSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    HzsSysConfig selectByPrimaryKey(Integer hsscId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    List<HzsSysConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsSysConfig record);
}