package com.hzsparrow.boot.base.mapper;

import com.hzsparrow.boot.base.entity.HzsUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HzsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hsuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_user
     *
     * @mbg.generated
     */
    int insert(HzsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_user
     *
     * @mbg.generated
     */
    HzsUser selectByPrimaryKey(String hsuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_user
     *
     * @mbg.generated
     */
    List<HzsUser> selectAll(@Param("hsuName") String hsuName, @Param("mobile") String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HzsUser record);

    int remove(@Param("deleteFlag") Integer deleteFlag, @Param("hsuId") String hsuId);

    int changePassword(@Param("hsuId") String hsuId, @Param("newPassword") String newPassword);

    HzsUser getByAccount(String hsuAccount);
}