server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://39.97.237.211:3306/hzsparrow-base?serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 2
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  config: classpath:logback-spring.xml
hzsparrow:
  fu:
    fileServerType: 1
mybatis:
  mapper-locations: classpath:com.hzsparrow.**.mapper/*.xml