server:
  port: 8082
  servlet:
    context-path: /
spring:
  profiles:
    active: test
logging:
  level:
    com.hzsparrow.boot.base.mapper: debug
mybatis:
  mapper-locations: classpath:com.hzsparrow.**.mapper/*.xml
hzsparrow:
  fileupload:
    serverType: local
