spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hzsparrow-base?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 2
    type: com.alibaba.druid.pool.DruidDataSource