package com.hzsparrow.business.base.entity;

import com.hzsparrow.framework.utils.tree.TreeModelSource;

import java.io.Serializable;

public class HzsDictionaryDetail implements Serializable, TreeModelSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.bdd_id
     *
     * @mbg.generated
     */
    private String hsddId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.bdt_id
     *
     * @mbg.generated
     */
    private String hsdtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.bdd_name
     *
     * @mbg.generated
     */
    private String hsddName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.int_value
     *
     * @mbg.generated
     */
    private Integer intValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.str_value
     *
     * @mbg.generated
     */
    private String strValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary_detail.sort_num
     *
     * @mbg.generated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.bdd_id
     *
     * @return the value of base_dictionary_detail.bdd_id
     *
     * @mbg.generated
     */
    public String getHsddId() {
        return hsddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.bdd_id
     *
     * @param hsddId the value for base_dictionary_detail.bdd_id
     *
     * @mbg.generated
     */
    public void setHsddId(String hsddId) {
        this.hsddId = hsddId == null ? null : hsddId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.bdt_id
     *
     * @return the value of base_dictionary_detail.bdt_id
     *
     * @mbg.generated
     */
    public String getHsdtId() {
        return hsdtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.bdt_id
     *
     * @param hsdtId the value for base_dictionary_detail.bdt_id
     *
     * @mbg.generated
     */
    public void setHsdtId(String hsdtId) {
        this.hsdtId = hsdtId == null ? null : hsdtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.bdd_name
     *
     * @return the value of base_dictionary_detail.bdd_name
     *
     * @mbg.generated
     */
    public String getHsddName() {
        return hsddName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.bdd_name
     *
     * @param hsddName the value for base_dictionary_detail.bdd_name
     *
     * @mbg.generated
     */
    public void setHsddName(String hsddName) {
        this.hsddName = hsddName == null ? null : hsddName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.int_value
     *
     * @return the value of base_dictionary_detail.int_value
     *
     * @mbg.generated
     */
    public Integer getIntValue() {
        return intValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.int_value
     *
     * @param intValue the value for base_dictionary_detail.int_value
     *
     * @mbg.generated
     */
    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.str_value
     *
     * @return the value of base_dictionary_detail.str_value
     *
     * @mbg.generated
     */
    public String getStrValue() {
        return strValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.str_value
     *
     * @param strValue the value for base_dictionary_detail.str_value
     *
     * @mbg.generated
     */
    public void setStrValue(String strValue) {
        this.strValue = strValue == null ? null : strValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.parent_id
     *
     * @return the value of base_dictionary_detail.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.parent_id
     *
     * @param parentId the value for base_dictionary_detail.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary_detail.sort_num
     *
     * @return the value of base_dictionary_detail.sort_num
     *
     * @mbg.generated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary_detail.sort_num
     *
     * @param sortNum the value for base_dictionary_detail.sort_num
     *
     * @mbg.generated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dictionary_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hsddId=").append(hsddId);
        sb.append(", hsdtId=").append(hsdtId);
        sb.append(", hsddName=").append(hsddName);
        sb.append(", intValue=").append(intValue);
        sb.append(", strValue=").append(strValue);
        sb.append(", parentId=").append(parentId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public Object getTreeModelId() {
        return getHsddId();
    }

    @Override
    public String getTreeModelName() {
        return getHsddName();
    }

    @Override
    public Object getTreeModelParentId() {
        return getParentId();
    }
}