package com.hzsparrow.business.base.entity;

import java.io.Serializable;

public class HzsSysConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_id
     *
     * @mbg.generated
     */
    private Integer hsscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_name
     *
     * @mbg.generated
     */
    private String hsscName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_flag
     *
     * @mbg.generated
     */
    private String hsscFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_value
     *
     * @mbg.generated
     */
    private String hsscValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_type
     *
     * @mbg.generated
     */
    private Integer hsscType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_refer_value
     *
     * @mbg.generated
     */
    private String hsscReferValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.hssc_group
     *
     * @mbg.generated
     */
    private String hsscGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hzs_sys_config.sort_num
     *
     * @mbg.generated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_id
     *
     * @return the value of hzs_sys_config.hssc_id
     *
     * @mbg.generated
     */
    public Integer getHsscId() {
        return hsscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_id
     *
     * @param hsscId the value for hzs_sys_config.hssc_id
     *
     * @mbg.generated
     */
    public void setHsscId(Integer hsscId) {
        this.hsscId = hsscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_name
     *
     * @return the value of hzs_sys_config.hssc_name
     *
     * @mbg.generated
     */
    public String getHsscName() {
        return hsscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_name
     *
     * @param hsscName the value for hzs_sys_config.hssc_name
     *
     * @mbg.generated
     */
    public void setHsscName(String hsscName) {
        this.hsscName = hsscName == null ? null : hsscName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_flag
     *
     * @return the value of hzs_sys_config.hssc_flag
     *
     * @mbg.generated
     */
    public String getHsscFlag() {
        return hsscFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_flag
     *
     * @param hsscFlag the value for hzs_sys_config.hssc_flag
     *
     * @mbg.generated
     */
    public void setHsscFlag(String hsscFlag) {
        this.hsscFlag = hsscFlag == null ? null : hsscFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_value
     *
     * @return the value of hzs_sys_config.hssc_value
     *
     * @mbg.generated
     */
    public String getHsscValue() {
        return hsscValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_value
     *
     * @param hsscValue the value for hzs_sys_config.hssc_value
     *
     * @mbg.generated
     */
    public void setHsscValue(String hsscValue) {
        this.hsscValue = hsscValue == null ? null : hsscValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_type
     *
     * @return the value of hzs_sys_config.hssc_type
     *
     * @mbg.generated
     */
    public Integer getHsscType() {
        return hsscType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_type
     *
     * @param hsscType the value for hzs_sys_config.hssc_type
     *
     * @mbg.generated
     */
    public void setHsscType(Integer hsscType) {
        this.hsscType = hsscType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_refer_value
     *
     * @return the value of hzs_sys_config.hssc_refer_value
     *
     * @mbg.generated
     */
    public String getHsscReferValue() {
        return hsscReferValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_refer_value
     *
     * @param hsscReferValue the value for hzs_sys_config.hssc_refer_value
     *
     * @mbg.generated
     */
    public void setHsscReferValue(String hsscReferValue) {
        this.hsscReferValue = hsscReferValue == null ? null : hsscReferValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.hssc_group
     *
     * @return the value of hzs_sys_config.hssc_group
     *
     * @mbg.generated
     */
    public String getHsscGroup() {
        return hsscGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.hssc_group
     *
     * @param hsscGroup the value for hzs_sys_config.hssc_group
     *
     * @mbg.generated
     */
    public void setHsscGroup(String hsscGroup) {
        this.hsscGroup = hsscGroup == null ? null : hsscGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hzs_sys_config.sort_num
     *
     * @return the value of hzs_sys_config.sort_num
     *
     * @mbg.generated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hzs_sys_config.sort_num
     *
     * @param sortNum the value for hzs_sys_config.sort_num
     *
     * @mbg.generated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hzs_sys_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hsscId=").append(hsscId);
        sb.append(", hsscName=").append(hsscName);
        sb.append(", hsscFlag=").append(hsscFlag);
        sb.append(", hsscValue=").append(hsscValue);
        sb.append(", hsscType=").append(hsscType);
        sb.append(", hsscReferValue=").append(hsscReferValue);
        sb.append(", hsscGroup=").append(hsscGroup);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}